config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications
  resources :shopping_order_comments
  resources :item_comments
  resources :vans
  resources :shipping_manifests
  resources :categories
  resources :boxes
  resources :packing_jobs
  resources :locations
  resources :items
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
  root to: "shop#index"
  resources :carts do
    resources :lineitems
  end
  resources :shopping_orders
  resources :lineitems
  get 'shop/index'
  get 'shop/floorLayout'
  get 'shop/pathSearch'
  get 'shop/usersList'
  

end

app/models/box.rb
class Box < ActiveRecord::Base
	has_many :items
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :lineitems, :dependent => :destroy
	belongs_to :user
	
	def addItem(item_id,quantity)
		current_item = lineitems.find_by_item_id(item_id) 
		if current_item
		current_item.quantity += quantity 
	else
		current_item = lineitems.new(item_id: item_id)
		current_item.quantity = quantity 
	end
		current_item 
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :lineitems, dependent: :destroy
	belongs_to :location
	has_one :box
	has_one :category

	def self.search(search)
	  where("title LIKE ?", "%#{search}%") 
	  
	end
end

app/models/item_comment.rb
class ItemComment < ActiveRecord::Base
	belongs_to :user, dependent: :destroy
	belongs_to :item
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :cart
    belongs_to :item
    belongs_to :shopping_order

    def sortingMethod(lineitem)
    weightPoints = lineitem.item.weight
    fragilePoints = 0
    if lineitem.item.fragile
        fragilePoints=60
    end
    box = Box.find(lineitem.item.boxId) 
    boxPoints = box.points


   returningpoints=weightPoints - fragilePoints + boxPoints

    end
    
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :item
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/packing_job.rb
class PackingJob < ActiveRecord::Base
	belongs_to :user
	belongs_to :shopping_order, dependent: :destroy
end

app/models/shipping_manifest.rb
class ShippingManifest < ActiveRecord::Base
	belongs_to :shoppingOrder
	
	def findDistanceForDelivery(shipping_manifest_id)
        @shipping_manifest=ShippingManifest.find(shipping_manifest_id)
         @shoppingorder = ShoppingOrder.find(@shipping_manifest.shoppingOrder_id) 
         @customer = User.find(@shoppingorder.customer_id)
         @customer.distance_to("DIT Aungier Street Dublin")
    end
    def findDistanceForNextStop(customer_address,shipping_manifest_id_to)
        @shipping_manifest=ShippingManifest.find(shipping_manifest_id_to)
         @shoppingorder = ShoppingOrder.find(@shipping_manifest.shoppingOrder_id) 
         @customer = User.find(@shoppingorder.customer_id)
         @customer.distance_to(customer_address)
    end
end

app/models/shopping_order.rb
class ShoppingOrder < ActiveRecord::Base
	belongs_to :user, dependent: :destroy
	has_one :packing_job
	has_many :lineitems, dependent: :destroy
	def add_lineitems_from_cart(cart)
	 cart.lineitems.each do |item|
		item.cart_id = nil
		lineitems << item 
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shopping_orders, dependent: :destroy
  has_many :packing_jobs
  geocoded_by :address, :units => :km
  after_validation :geocode, :if => :address_changed?
  
end

app/models/van.rb
class Van < ActiveRecord::Base
end

app/controllers/vans_controller.rb
class VansController < ApplicationController
  before_action :set_van, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!
  before_action :must_be_admin_or_driver, only: [:edit, :update,:index,:show,:destroy,:new,:create]
  

  # GET /vans
  # GET /vans.json
  def index
    @vans = Van.all
  end

  # GET /vans/1
  # GET /vans/1.json
  def show
  end

  # GET /vans/new
  def new
    @van = Van.new
  end

  # GET /vans/1/edit
  def edit
  end

  # POST /vans
  # POST /vans.json
  def create
    @van = Van.new(van_params)

    respond_to do |format|
      if @van.save
        format.html { redirect_to @van, notice: 'Van was successfully created.' }
        format.json { render :show, status: :created, location: @van }
      else
        format.html { render :new }
        format.json { render json: @van.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vans/1
  # PATCH/PUT /vans/1.json
  def update
    respond_to do |format|
      if @van.regPlate == van_params["regPlate"]
        # first point
        @current_shipping_manifests = ShippingManifest.where(shippingstatus: "Packed ready to ship").where(vanID: nil).sort {|a,b|  a.findDistanceForDelivery(a.id)<=>b.findDistanceForDelivery(b.id)  }
        if @current_shipping_manifests[0] != nil
        shippingHash = Hash.new
        shippingHash["vanID"]=@van.id
        shippingHash["shippingStatus"]="Shipping"
        @current_shipping_manifests[0].update(shippingHash)
        @firstShoppingOrder = ShoppingOrder.find(@current_shipping_manifests[0].shoppingOrder_id)
        @first_location_user = User.find(@firstShoppingOrder.customer_id)
        # remaining 6 spots
        @following_shipping_manifests = ShippingManifest.where(shippingstatus: "Packed ready to ship").where(vanID: nil).sort {|a,b|  a.findDistanceForNextStop(@first_location_user.address,a.id)<=>b.findDistanceForNextStop(@first_location_user.address,b.id) }
        followingshippingHash = Hash.new
        followingshippingHash["vanID"]=@van.id
        followingshippingHash["shippingStatus"]="Shipping"
        if @following_shipping_manifests.length > 3
          @following_shipping_manifests[0].update(followingshippingHash)
          @following_shipping_manifests[1].update(followingshippingHash)
          @following_shipping_manifests[2].update(followingshippingHash)
        else
          @following_shipping_manifests.each do |shippingMan|
            shippingMan.update(followingshippingHash)
          end

        end
        @message="Van has been packed"
        @adminnoti=createAdminNotification(@van.id, @message)
        @drivernoti=createDriverNotificationNewJob(@van.id,@van.driverID, @message)
      end

      end
      if @van.update(van_params)
        
        
        format.html { redirect_to @van }
        format.json { render :show, status: :ok, location: @van }
      else
        format.html { render :edit }
        format.json { render json: @van.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vans/1
  # DELETE /vans/1.json
  def destroy
    @van.destroy
    respond_to do |format|
      format.html { redirect_to vans_url, notice: 'Van was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_van
      @van = Van.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def van_params
      params.require(:van).permit(:regPlate)
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vans_helper.rb
module VansHelper
end

app/views/vans/_form.html.erb
<%= form_for(@van) do |f| %>
  <% if @van.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@van.errors.count, "error") %> prohibited this van from being saved:</h2>

      <ul>
      <% @van.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :regPlate %><br>
    <%= f.text_field :regPlate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vans/edit.html.erb
<h1>Editing Van</h1>

<%= render 'form' %>

<%= link_to 'Show', @van %> |
<%= link_to 'Back', vans_path %>

app/views/vans/index.html.erb
<h1>Listing Vans</h1>

<table>
  <thead>
    <tr>
      <th>Regplate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vans.each do |van| %>

      <tr>
        <td><%= van.regPlate %></td>
        <td><% @vans_shipping_manifests = ShippingManifest.where(vanID: van.id).where(shippingstatus: ["Packed ready to ship","Shipping"]) 
        counter=0
          @vans_shipping_manifests.each do |shipping_manifest| 
            counter = counter+1
          end
        %>
        <%= counter%> Orders still in the van</td>
        <td><%= link_to 'Show', van %></td>

        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if current_user.is_admin? %>
<%= link_to 'New Van', new_van_path %>
<%end%>

app/views/vans/new.html.erb
<h1>New Van</h1>

<%= render 'form' %>

<%= link_to 'Back', vans_path %>

app/views/vans/show.html.erb
<p>
  <strong>Regplate:</strong>
  <%= @van.regPlate %>
</p>


<% @vans_shipping_manifests = ShippingManifest.where(vanID: @van.id).where(shippingStatus: "Shipping").sort {|a,b|  a.findDistanceForDelivery(a.id)<=>b.findDistanceForDelivery(b.id) }%>
<%if @vans_shipping_manifests[0]!=nil %>
<% @shoppingorder = ShoppingOrder.find(@vans_shipping_manifests[0].shoppingOrder_id) %>
<% @user = User.find(@shoppingorder.customer_id) %>

<% @shipping_manifests_new_order = ShippingManifest.where(shippingstatus: "Shipping").where(vanID: @van.id).sort {|a,b|  a.findDistanceForNextStop(@user.address,a.id)<=>b.findDistanceForNextStop(@user.address,b.id)  }%>

<% @shipping_manifests_new_order.each do |shipping_manifest| %>
      <div class="col-sm-12 possition-<%=@shipping_manifests_new_order.index(shipping_manifest)%>">
       <div class="col-sm-6">
		<% @shoppingorder = ShoppingOrder.find(shipping_manifest.shoppingOrder_id) %>
		<% @customer = User.find(@shoppingorder.customer_id)%>
		<h2>Delivering to: <strong><%= @customer.name %></strong></h2>
		<h4>At: <strong><%= @customer.address %></strong></h4>
		<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@customer.latitude}%2C#{@customer.longitude}" %>
		</div>

		<div class="col-sm-6">
<div class="col-sm-12 text-center">
			<%= form_for(shipping_manifest) do |f| %>
				  
				  
				
				    <%= f.hidden_field :shippingStatus , :value => "Delivered"%>
				  
				  
				    <%= f.submit "Deliver", :class => "btn btn-lg btn-primary DeliverButton" %>
				  
				<% end %>
			</div>

<p><%= link_to 'Printable Receipt (PDF)', shopping_order_path(@shoppingorder, format: "pdf"), :class => "btn btn-primary pull-right" %></p>

<div class="col-sm-12">
<h3>Items to Deliver for shopping order #<%= @shoppingorder.id%></h3>
</div>
<table>
	<tr>
		<th>Quantity</th>
		<th style="padding-left:20px; padding-right:20px;">Title</th>
		<th>Total</th>
	</tr>

<% @shoppingorder.lineitems.each do |litem| %> 
<tr>
<td><%= litem.quantity %> &times;</td>
 <td style="padding-left:20px; padding-right:20px;">
  <%= litem.item.title %>
 </td> 
<td>
  <%= number_to_currency(litem.item.price * litem.quantity, :unit => '€' ) %>
</td>

</tr>
<% end %> 
</table>





			<h2>These will be the next stops</h2>
			<% position_in_array= @shipping_manifests_new_order.index(shipping_manifest)%>
			<% counter=position_in_array+1%>
			<% total_length = @shipping_manifests_new_order.length%>
			<% while counter < total_length  do %>
				<% @shoppingorder = ShoppingOrder.find(@shipping_manifests_new_order[counter].shoppingOrder_id) %>
				<% @customer = User.find(@shoppingorder.customer_id)%>
				<h4>At: <strong><%= @customer.address %></strong></h4>
				<script  type="text/javascript">
					  jQuery(document).ready(function($) {
					      $(".possition-<%=counter%>").addClass("hidden");
					  });
					  </script>
				<%counter=counter+1%>
				<%end%>
				

		</div>
      </div>
      <%end%>
      <%end%>
<%if current_user.is_admin? %>
<script>
jQuery(document).ready(function($) {
      $('.DeliverButton').addClass("disabled");
      });
</script>


<%end%>

<%= link_to 'Edit', edit_van_path(@van) %> |
<%= link_to 'Back', vans_path %>