config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications
  resources :shopping_order_comments
  resources :item_comments
  resources :vans
  resources :shipping_manifests
  resources :categories
  resources :boxes
  resources :packing_jobs
  resources :locations
  resources :items
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
  root to: "shop#index"
  resources :carts do
    resources :lineitems
  end
  resources :shopping_orders
  resources :lineitems
  get 'shop/index'
  get 'shop/floorLayout'
  get 'shop/pathSearch'
  get 'shop/usersList'
  

end

app/models/box.rb
class Box < ActiveRecord::Base
	has_many :items
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :lineitems, :dependent => :destroy
	belongs_to :user
	
	def addItem(item_id,quantity)
		current_item = lineitems.find_by_item_id(item_id) 
		if current_item
		current_item.quantity += quantity 
	else
		current_item = lineitems.new(item_id: item_id)
		current_item.quantity = quantity 
	end
		current_item 
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :lineitems, dependent: :destroy
	belongs_to :location
	has_one :box
	has_one :category

	def self.search(search)
	  where("title LIKE ?", "%#{search}%") 
	  
	end
end

app/models/item_comment.rb
class ItemComment < ActiveRecord::Base
	belongs_to :user, dependent: :destroy
	belongs_to :item
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :cart
    belongs_to :item
    belongs_to :shopping_order

    def sortingMethod(lineitem)
    weightPoints = lineitem.item.weight
    fragilePoints = 0
    if lineitem.item.fragile
        fragilePoints=60
    end
    box = Box.find(lineitem.item.boxId) 
    boxPoints = box.points


   returningpoints=weightPoints - fragilePoints + boxPoints

    end
    
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :item
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/packing_job.rb
class PackingJob < ActiveRecord::Base
	belongs_to :user
	belongs_to :shopping_order, dependent: :destroy
end

app/models/shopping_order.rb
class ShoppingOrder < ActiveRecord::Base
	belongs_to :user, dependent: :destroy
	has_one :packing_job
	has_many :lineitems, dependent: :destroy
	def add_lineitems_from_cart(cart)
	 cart.lineitems.each do |item|
		item.cart_id = nil
		lineitems << item 
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shopping_orders, dependent: :destroy
  has_many :packing_jobs
  geocoded_by :address, :units => :km
  after_validation :geocode, :if => :address_changed?
  
end

app/models/van.rb
class Van < ActiveRecord::Base
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :must_be_admin, only: [:index,:show,:destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to :back, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:fromID, :toID, :message, :regardingID, :seen)
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vans_helper.rb
module VansHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fromID %><br>
    <%= f.number_field :fromID %>
  </div>
  <div class="field">
    <%= f.label :toID %><br>
    <%= f.number_field :toID %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :regardingID %><br>
    <%= f.number_field :regardingID %>
  </div>
  <div class="field">
    <%= f.label :seen %><br>
    <%= f.check_box :seen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>
<%@notifications = Notification.where(toID: current_user.id)%>
<h1>Listing Notifications</h1>

<table style="width:100%;">
  <thead>
    <tr>
      <th>Message</th>
      <th>Regardingid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.message %></td>
        <td><%= notification.regardingID %></td>
        
          <%if !notification.seen? %>
          <td>
        <%= form_for(notification) do |f| %>

  
                    <%= f.hidden_field :seen,  :value => '1' %>
                 
                  
                    <%= f.submit "Dismiss",:class=>"btn btn-default "  %>
                  
                  <% end %>
                </td>
             <%end%>     
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fromid:</strong>
  <%= @notification.fromID %>
</p>

<p>
  <strong>Toid:</strong>
  <%= @notification.toID %>
</p>

<p>
  <strong>Message:</strong>
  <%= @notification.message %>
</p>

<p>
  <strong>Regardingid:</strong>
  <%= @notification.regardingID %>
</p>

<p>
  <strong>Seen:</strong>
  <%= @notification.seen %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>