config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications
  resources :shopping_order_comments
  resources :item_comments
  resources :vans
  resources :shipping_manifests
  resources :categories
  resources :boxes
  resources :packing_jobs
  resources :locations
  resources :items
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
  root to: "shop#index"
  resources :carts do
    resources :lineitems
  end
  resources :shopping_orders
  resources :lineitems
  get 'shop/index'
  get 'shop/floorLayout'
  get 'shop/pathSearch'
  get 'shop/usersList'
  

end

app/models/box.rb
class Box < ActiveRecord::Base
	has_many :items
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :lineitems, :dependent => :destroy
	belongs_to :user
	
	def addItem(item_id,quantity)
		current_item = lineitems.find_by_item_id(item_id) 
		if current_item
		current_item.quantity += quantity 
	else
		current_item = lineitems.new(item_id: item_id)
		current_item.quantity = quantity 
	end
		current_item 
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :lineitems, dependent: :destroy
	belongs_to :location
	has_one :box
	has_one :category

	def self.search(search)
	  where("title LIKE ?", "%#{search}%") 
	  
	end
end

app/models/item_comment.rb
class ItemComment < ActiveRecord::Base
	belongs_to :user, dependent: :destroy
	belongs_to :item
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :cart
    belongs_to :item
    belongs_to :shopping_order

    def sortingMethod(lineitem)
    weightPoints = lineitem.item.weight
    fragilePoints = 0
    if lineitem.item.fragile
        fragilePoints=60
    end
    box = Box.find(lineitem.item.boxId) 
    boxPoints = box.points


   returningpoints=weightPoints - fragilePoints + boxPoints

    end
    
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :item
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/packing_job.rb
class PackingJob < ActiveRecord::Base
	belongs_to :user
	belongs_to :shopping_order, dependent: :destroy
end

app/models/shipping_manifest.rb
class ShippingManifest < ActiveRecord::Base
	belongs_to :shoppingOrder
	
	def findDistanceForDelivery(shipping_manifest_id)
        @shipping_manifest=ShippingManifest.find(shipping_manifest_id)
         @shoppingorder = ShoppingOrder.find(@shipping_manifest.shoppingOrder_id) 
         @customer = User.find(@shoppingorder.customer_id)
         @customer.distance_to("DIT Aungier Street Dublin")
    end
    def findDistanceForNextStop(customer_address,shipping_manifest_id_to)
        @shipping_manifest=ShippingManifest.find(shipping_manifest_id_to)
         @shoppingorder = ShoppingOrder.find(@shipping_manifest.shoppingOrder_id) 
         @customer = User.find(@shoppingorder.customer_id)
         @customer.distance_to(customer_address)
    end
end

app/models/shopping_order.rb
class ShoppingOrder < ActiveRecord::Base
	belongs_to :user, dependent: :destroy
	has_one :packing_job
	has_many :lineitems, dependent: :destroy
	def add_lineitems_from_cart(cart)
	 cart.lineitems.each do |item|
		item.cart_id = nil
		lineitems << item 
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shopping_orders, dependent: :destroy
  has_many :packing_jobs
  geocoded_by :address, :units => :km
  after_validation :geocode, :if => :address_changed?
  
end

app/models/van.rb
class Van < ActiveRecord::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :must_be_admin, only: [:edit, :update,:index]
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.lineitems.each do |litem| 
      item = Item.find(litem.item_id) 
      @quantityremaining = item.quantity + litem.quantity
      itemHash= Hash.new
      itemHash["quantity"]=@quantityremaining
      item.update(itemHash)
      litem.destroy
    end
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Cart was successfully destroyed.' }
      session[:cart_id]=nil
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vans_helper.rb
module VansHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<table>
	<tr>
		<th style="width:20%; padding-right:15px;">Quantity</th>
		<th style="width:20%; padding-right:15px;">Title</th>
		<th style="width:20%; padding-right:15px;">Price Per Item</th>
		<th style="width:20%; padding-right:15px;">Total Price</th>
	</tr>
<% @cart.lineitems.each do |litem| %> 
	<tr>
		<td><%= litem.quantity %> &times;</td> 
		<td><%= litem.item.title %></td> 
		<td><%= litem.item.title %></td> 
		<td><%= number_to_currency(litem.item.price, :unit => '€' )  %></td>
		<td><%= link_to  litem, method: :delete, data: { confirm: 'Are you sure?' } do %>
			<i class="fa fa-times"></i> Remove
		<% end %>
	</td>
	</tr>
<% end %> 
</table>
<hr>
<div class="btn-group">
<%= link_to "Continue Shopping?", root_path, :method => :get, :class => "btn btn-default"  %>
<%= link_to 'Empty cart', @cart, method: :delete, confirm: 'Are you sure?', :class => "btn btn-default"   %>
<%= link_to 'Checkout', new_shopping_order_path, :method => :get, :class => "btn btn-default"   %>
</div>