config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications
  resources :shopping_order_comments
  resources :item_comments
  resources :vans
  resources :shipping_manifests
  resources :categories
  resources :boxes
  resources :packing_jobs
  resources :locations
  resources :items
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
  root to: "shop#index"
  resources :carts do
    resources :lineitems
  end
  resources :shopping_orders
  resources :lineitems
  get 'shop/index'
  get 'shop/floorLayout'
  get 'shop/pathSearch'
  get 'shop/usersList'
  

end

app/models/box.rb
class Box < ActiveRecord::Base
	has_many :items
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :lineitems, :dependent => :destroy
	belongs_to :user
	
	def addItem(item_id,quantity)
		current_item = lineitems.find_by_item_id(item_id) 
		if current_item
		current_item.quantity += quantity 
	else
		current_item = lineitems.new(item_id: item_id)
		current_item.quantity = quantity 
	end
		current_item 
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :lineitems, dependent: :destroy
	belongs_to :location
	has_one :box
	has_one :category

	def self.search(search)
	  where("title LIKE ?", "%#{search}%") 
	  
	end
end

app/models/item_comment.rb
class ItemComment < ActiveRecord::Base
	belongs_to :user, dependent: :destroy
	belongs_to :item
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :cart
    belongs_to :item
    belongs_to :shopping_order

    def sortingMethod(lineitem)
    weightPoints = lineitem.item.weight
    fragilePoints = 0
    if lineitem.item.fragile
        fragilePoints=60
    end
    box = Box.find(lineitem.item.boxId) 
    boxPoints = box.points


   returningpoints=weightPoints - fragilePoints + boxPoints

    end
    
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :item
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/packing_job.rb
class PackingJob < ActiveRecord::Base
	belongs_to :user
	belongs_to :shopping_order, dependent: :destroy
end

app/models/shopping_order.rb
class ShoppingOrder < ActiveRecord::Base
	belongs_to :user, dependent: :destroy
	has_one :packing_job
	has_many :lineitems, dependent: :destroy
	def add_lineitems_from_cart(cart)
	 cart.lineitems.each do |item|
		item.cart_id = nil
		lineitems << item 
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shopping_orders, dependent: :destroy
  has_many :packing_jobs
  geocoded_by :address, :units => :km
  after_validation :geocode, :if => :address_changed?
  
end

app/models/van.rb
class Van < ActiveRecord::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :must_be_admin, only: [:edit, :update,:index,:destroy, :create, :new]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @items = Item.where(categoryID: @category.id)
    @lineitem = Lineitem.new
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vans_helper.rb
module VansHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%if current_user && current_user.is_admin? %>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
<%end%>
<div class="col-sm-9">
  <div class="alert alert-info">
<h1><%= @category.name %></h1>
</div>
<%if !@items.empty?%>
  <% @items.each do |item| %>
  <% if item.quantity == 0%>
  

  <% else %>
  <h4><%= link_to item.title, item %></h4>
  <div class="col-sm-12" style="border-bottom: 1px solid #eee; padding-bottom: 10px;">
    <div class="col-sm-9">
      <div class="form-group">
        <div class="col-sm-8">
        <img src="<%= item.image %>" style="width:20px; heigth: 20px;">
        <%= number_to_currency(item.price, :unit => '€' ) %> Weight:<%= item.weight %> kg  </div>
        
        
        
  
<%= form_for(@lineitem) do |f| %>
  

  <div class="field">
    <%= f.hidden_field :item_id, :value =>  item.id   %>
  </div>
  
  
  <div class="col-sm-4">
    <%= f.number_field :quantity, :class => " text-center form-control bfh-number pull-right", :value => 1 ,:min => 1, :max => item.quantity%>
  </div>
    </div>

  </div>
  <div class="col-sm-3">
  <%= f.submit 'Add to Cart',:class => "btn btn-success pull-right" %>
  </div>
  
<%end%>
  </div>
  <%end%>
  <%end%>
  <% else %>
  <h2>We currently do not have stock of any items in this category</h2>
  <% end %>
</div>
<div class="col-sm-3">  
  
  <% if session[:cart_id]!=nil%>
  <h3>Your Current cart</h3>
  <% @cart = Cart.find(session[:cart_id])
   @total = 0
    @cart.lineitems.each do |litem| %> 
    
      <p><%= litem.quantity %> &times; <%= litem.item.title %> <%= number_to_currency(litem.item.price, :unit => '€' )  %> <%= link_to  litem, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fa fa-times "></i> </p>
      <% end %>
      <% @total = @total + (litem.item.price* litem.quantity)%>
    
    <% end %> 
    <hr>

    <h5 class="pull-right">Total in Basket: <strong><%= number_to_currency(@total, :unit => '€' )%></strong></h5>
    
    <div class="btn-group pull-right">
      <%= link_to 'Empty cart', @cart, method: :delete, confirm: 'Are you sure?', :class => "btn btn-default"   %>
      <%= link_to 'Checkout', new_shopping_order_path, :method => :get, :class => "btn btn-default"   %>
      </div>

<% end %>

<div class="col-sm-12" style="padding-right:0;">
  <hr>
<h3>Browse by category</h3> 
<% @categories = Category.all%>
<div class="list-group panel">
<% @categories.each do |category| %>
      
        <%= link_to category.name , category, :class => "list-group-item list-group-item-default" %>
        
      
    <% end %>
    </div>
  </div>
</div>

<script>
jQuery(document).ready(function($) {
      $('li').find('a:contains("<%= @category.name %>")').parent().addClass("alert alert-success");
      });




</script>